<html>
<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  			crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

	<link rel="stylesheet" type="text/css" href="/css/style.css">

</head>

<body>
	<header>
		<nav class="navbar navbar-expand-md navbar-light bg-dark" 
		style="border-bottom: 1px solid #999">
			<div class="container">
				<!-- logo -->
				<a href="#" class="navbar-brand">
					<div class="sr-only">Plataforma do ENEM</div>
				</a>

				<!-- botao de hamburger -->
				<button class="navbar-toggler" data-toggle="collapse" data-target="#main-navigation-area">
					<span class="navbar-toggler-icon"></span>
				</button>

				<!-- div para agrupar todos os elementos que serão escodindios em telas pequenas -->
				<div class="collapse navbar-collapse" id="main-navigation-area">
					<!-- menu -->
					<ul class="navbar-nav mr-5 ml-auto">
						<li class="nav-item">
							<a href="/cadastrar" class="nav-link text-light">Cadastrar</a>
						</li>
						<li class="nav-item">
							<a href="/login" class="nav-link text-light">Login</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>

	
	<?= $this->content() ?>

	<footer class="py-3 bg-light text-center" class="footer-element">
		Plataforma ONLINE de estudos para o ENEM. &copy; Batista Tiago & Abílio Neto (2019)
	</footer>

</body>

</html>