<section id="section-login" class='d-flex'>
	<div class="container align-self-center">
		<div class="row d-flex">
			<h1 class="display-2 bt-centralized-element">Página de Login</h1>

			<div class="bt-centralized-element col-12 w-75 bt-bg-gray p-3">
				<form action="/processar_login" method="post">
					<div class="container">
						<div class="row d-flex justify-content-around">



							<div id="studentEmailContainer" class="col-md-6 bt-centralized-element form-group">
								<label>Email: </label>
								<input autocomplete="off" class="form-control bt-default-form-control" id="studentEmailTextField" name="studentEmail" type="email" placeholder="Digite seu email">
							</div>
							<div class="col-md-6 bt-centralized-element form-group">
								<label>Senha: </label>
								<input class="form-control bt-default-form-control" id="studentPasswordTextField" name="studentPassword" type="password" placeholder="Digite sua senha">
							</div>
							<button class="col-md-2 btn btn-outline-dark bt-centralized-element btn-info-block" type="submit">Login</button>


						</div>
					</div>
					<? if (isset($this->view->info)) { ?>

						<script src="/scripts/feedbackLogin.js"></script>
						
						<? if ($this->view->info == 'erro') { ?>

							<div class="div-feedback">
								<span class="mensagem-feedback text-white bg-danger d-block lead text-center py-2 mt-3">
									Usuário ou senha incorretos
								</span>	
							</div>

						<? } else if ($this->view->info == 'usuario_inativo') { ?>

							<div class="div-feedback">
								<span class="mensagem-feedback text-dark bg-warning d-block lead text-center py-2 mt-3">
									Usuario inativo, confirme no endereço de email cadastrado.
								</span>	
							</div>

						<?} else if ($this->view->info == 'sessao_expirada') { ?>

							<div class="div-feedback">
								<span class="mensagem-feedback text-dark bg-warning d-block lead text-center py-2 mt-3">
									Sessão expirada - favor fazer login.
								</span>	
							</div>

						<?} else if ($this->view->info == 'conta_ativada') { ?>

							<div class="div-feedback">
								<span class="mensagem-feedback text-light bg-success d-block lead text-center py-2 mt-3">
									Usuario ativado - você pode fazer login.
								</span>	
							</div>

						<? }
					}?>
				</div>
			</form>

<!-- 				<form action="" method="post" class="mt-5 pt-5">

					<div class="centralized-element elemento-bordado w-100">
						<label>Email: </label>
						<input class="ml-1" type="text" name="userEmail">	
						<label class="ml-4">Senha: </label>
						<input class="ml-1" type="password" name="userPassword">	
					</div>
					<div class="d-flex justify-content-center my-3">
						<button class="btn btn-info" type="submit">Login</button>	
					</div>

				</form> -->
			</div>
		</div>
	</div>
</section>