<section id="section-login" class='d-flex'>
	<div class="container align-self-center">
		<div class="row d-flex">
			<div class="bt-centralized-element col-12 w-75 bt-bg-gray p-3 bt-rounded-border-10 text-dark">
				<h1 class="display-4 text-center">Recuperar Senha</h1>
				<div>
					<p class="lead text-center mb-4">Insira seu email no campo abaixo para iniciar o processo de recuperação de senha</p>	
					<div class="mx-3 d-flex justify-content-center">
						<form class="d-block w-50 py-2" action="/processar_redefinicao_senha" method="post">
							<div class="input-group">
								<input type="email" placeholder="Digite seu email" name="studentEmail" class="form-control bt-default-form-control">	
								<div class="input-group-append">
									<button type="submit" class="btn btn-outline-dark bt-centralized-element">Redefinir Senha</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>