<section id="section-login" class='d-flex'>
	<div class="container align-self-center">
		<div class="row d-flex">
			
			<div class="bt-centralized-element col-12 w-75 bg-success p-3 bt-rounded-border-10">
				<h1 class="display-2 text-center text-light">Sucesso ao cadastrar</h1>
				<p class="lead text-light mb-5 text-center">Verifique o link enviado para o email cadastrado.</p>
				<a href="/login" class="btn btn-outline-light col-md-2 btn-block bt-centralized-element">Login</a>
			</div>

		</div>
	</div>
</section>