<section id="section-login" class='d-flex'>
	<div class="container align-self-center">
		<div class="row d-flex">
			
			<div class="bt-centralized-element col-12 w-75 bt-bg-gray p-3 bt-rounded-border-10">
				<h1 class="display-2 text-center text-success">Sucesso!</h1>
				<div class="text-dark mb-5">
					<p class="lead text-center">Confirme o seu email acessando o link enviado.</p>	
					<div class="mx-5 px-5 text-justify">Por motivos de segurança é necessário que estudantes recém cadastrados confirmem o endereço de email cadastrado no sistema. Para isso, acesse o link enviado.</div>
				</div>

				
				<a href="/login" class="btn btn-outline-dark col-md-2 btn-block bt-centralized-element">Login</a>
			</div>

		</div>
	</div>
</section>